# Site settings
title: Notes from the lab
email:  mail@bad-science.net
description: > # this means to ignore newlines until "baseurl:"
  Just notes about what i found out about $stuff in the intertubes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  pappelt

# Build settings
markdown: kramdown
