# Site settings
title: Notes from bad-science.net
email:  mail@bad-science.net
description: > # this means to ignore newlines until "baseurl:"
  Ohai, you just found my loose-leaf collection of things i found or thought while coding.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pappelt.github.io" # the base hostname & protocol for your site
github_username:  pappelt

# Build settings
markdown: kramdown
